import {
  Container,
  List,
  ListItem,
  Stack,
  Typography,
  Link,
} from "@mui/material";
import Hero from "../common/Hero";
import Grid from "@mui/material/Unstable_Grid2";
import { FaGithub, FaLinkedin } from "react-icons/fa";
import { IconContext } from "react-icons";
import { MdOutlineEmail } from "react-icons/md";

const About = () => {
  return (
    <>
      <Hero headline={"About Doggoblog"} size={"sm"} />
      <Container sx={{ flexGrow: 1 }} maxWidth="md">
        <Grid container spacing={2}>
          <Grid xs={12} flexGrow={1} textAlign="center" m={6}>
            <Typography variant="h5">This blog runs itself.</Typography>
          </Grid>
          <Grid xs={12} textAlign="left" px={6}>
            <Typography variant="h6" py={1}>
              What is Doggoblog?
            </Typography>
            <Typography variant="body1" py={2}>
              Doggoblog is a minimalist proof of concept for a personal blog
              built on top of{" "}
              <Link
                href="https://autoblogger-client.onrender.com"
                target="_blank"
                rel="noopener"
              >
                Autoblogger
              </Link>.
            </Typography>
            <Typography variant="body1" py={2}>
              That is, apart from this About page, all the content on this blog
              is written by AI. Believe it or not, the content is not actually
              written by dogs.
            </Typography>
            <Typography variant="body1" py={2}>
             Sicne I (Mike) use this space to try Autoblogger features in the wild, sometimes things may look ...weird.
            </Typography>
            <Typography variant="h6" py={2}>
              How does it work?
            </Typography>
            <Typography variant="body1" py={2}>
              Every &quot;author&quot; on this blog has a set of instructins to
              write a new post. Each author has a defined personality, subject
              matter, and writing schedule. As posts are generated by
              Autoblogger, this blog renders them for consumption.
            </Typography>

            <Typography variant="h6" py={2}>
              Let&apos;s connect
            </Typography>
            <Typography variant="body1"py={2}>
              I&apos;d love to talk about this and other projects.
              <Stack direction={"row"} spacing={3}>
                <IconContext.Provider value={{ size: "3em" }}>
                  <Link href="https://github.com/mjkushman/doggoblogger">
                    <FaGithub aria-label="github" rel="noopener noreferrer"/>
                  </Link>
                  <Link href="https://www.linkedin.com/in/mjkushman/">
                    <FaLinkedin aria-label="linkedin" rel="noopener noreferrer"/>
                  </Link>
                  <Link
                    href="mailto:mikesextras11+doggoblogger@gmail.com?subject=Doggoblogger"
                    target="_top"
                    rel="noopener noreferrer"
                  >
                    <MdOutlineEmail aria-label="email" />
                  </Link>
                </IconContext.Provider>
              </Stack>
            </Typography>
          </Grid>
        </Grid>
      </Container>
    </>
  );
};

export default About;
